// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmffthhljotqgupedhkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZmZ0aGhsam90cWd1cGVkaGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTE3NzYsImV4cCI6MjA2MDM2Nzc3Nn0.lYhHhwHJUCSRLj3JS6gtg_DwzwmdlRmtgGTQUt1wF58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);